name: Deploy docker image to server
on:
  push:
    branches: [ master ]

env:
  SSH_KEY: "${{ secrets.DEPLOY_KEY }}"
  SSH_USER: "${{ secrets.DEPLOY_USERNAME }}"
  SSH_HOST: "${{ secrets.DEPLOY_HOST }}"
  SSH_PORT: "22"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GHCR_PAT }}
  
jobs:
  deploy:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Remote Docker Login
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "$SSH_KEY")
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh -p$SSH_PORT $SSH_USER@$SSH_HOST 'sudo docker login '$REGISTRY' --username '$REGISTRY_USERNAME' --password '$REGISTRY_PASSWORD 
      - name: Remote Docker PULL
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "$SSH_KEY")
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh -p$SSH_PORT $SSH_USER@$SSH_HOST 'sudo docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest'
